Added result
js-tasks-ru/jsbasic-20240321_dzmitrymanuilau pull request #1
Opened 2024-03-26 10:16 UTC by DzmitryManuilau

Solving two math examples through a function

2024-03-26 10:16 UTC, jsru commented
Спасибо за отправленный пулриквест, теперь @SinimaWath должен запустить тесты.

2024-03-26 16:41 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2024-03-26 16:42 UTC, SinimaWath requested changes

2024-03-26 16:42 UTC, SinimaWath commented on 0-module/1-task/index.js
> +  alert (result2);
Из задачи надо убрать весь лишний код, должна остаться только функция с решением задачи

2024-03-28 16:14 UTC, DzmitryManuilau commented on 0-module/1-task/index.js
> +  alert (result2);
Готово

2024-03-30 10:52 UTC, SinimaWath approved these changes

2024-03-30 10:52 UTC, SinimaWath commented on 0-module/1-task/index.js
> +console.log(sum(2, 5));
Надо убрать из задачи лишний код

2024-03-30 10:52 UTC, SinimaWath commented on 1-module/1-task/index.js
> +console.log(factorial(3));
Тут тоже давай уберем

2024-03-30 10:52 UTC, merged