Tasks solved
js-tasks-ru/jsbasic-20240321_dzmitrymanuilau pull request #2
Opened 2024-04-03 09:41 UTC by DzmitryManuilau

2024-04-03 09:41 UTC, jsru-1 commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2024-04-05 14:56 UTC, SinimaWath requested changes

2024-04-05 14:56 UTC, SinimaWath commented on 3-module/2-task/index.js
> +  }
Давай тут использовать: `arr.filter().map()`

2024-04-08 11:46 UTC, jsru-1 commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2024-04-08 12:04 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2024-04-08 12:18 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2024-04-08 12:45 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2024-04-08 12:46 UTC, DzmitryManuilau commented on 3-module/2-task/index.js
> +  }
Сделал

2024-04-09 19:42 UTC, SinimaWath approved these changes
все круто

2024-04-09 19:43 UTC, merged