8-module
js-tasks-ru/jsbasic-20240321_dzmitrymanuilau pull request #6
Opened 2024-04-29 13:36 UTC by DzmitryManuilau

2024-04-29 13:37 UTC, jsru-1 commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2024-04-29 13:40 UTC, DzmitryManuilau commented
Цитата из 8.1

«Обращаем ваше внимание, что в связи с тем, что это задание может быть
решено многими способами, его достаточно сложно проверить автоматически.
Поэтому если вы сталкнетесь с ситуацией, что в браузере всё работает как
надо, но тесты не проходят, обращайтесь к преподавателю за помощью.» Что
мне делать, если два теста код не проходит?


On Mon, 29 Apr 2024 at 16:38, javascriptru ***@***.***> wrote:

> Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет
> принят до тех пор, пока *все* добавленные задачи не будут решены).
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/js-tasks-ru/jsbasic-20240321_dzmitrymanuilau/pull/6#issuecomment-2082778248>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZTADG275APCXV5YG6I7QJLY7ZEMFAVCNFSM6AAAAABG6LKOACVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDAOBSG43TQMRUHA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***
> com>
>

2024-04-29 14:25 UTC, jsru-1 commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2024-04-30 15:45 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2024-04-30 19:13 UTC, jsru-1 commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2024-04-30 19:34 UTC, jsru-1 commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2024-05-01 11:22 UTC, SinimaWath requested changes

2024-05-01 11:22 UTC, SinimaWath commented on 9-module/2-task/index.js
> +});
Вот этот код надо убрать :)

2024-05-01 11:22 UTC, SinimaWath commented on 9-module/2-task/index.js
> +    this.initEventListeners();
Весь код надо перенести в метод `render` constructor должен быть пустым

2024-05-01 19:39 UTC, jsru-1 commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2024-05-02 15:39 UTC, SinimaWath approved these changes
Тепер все круто

2024-05-02 15:40 UTC, merged